services:

#    wsse.security.authentication.provider:
#        class: Initiative\AppBundle\Security\Authentication\Provider\WsseProvider
#        arguments: ["", "%kernel.cache_dir%/security/nonces"]
#        
#    apikey.security.authentication.listener:
#        class: Initiative\AppBundle\Security\ApiKeyFirewallListener
#        arguments: ["@security.token_storage","@security.authentication.manager"]