security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        wsse_secured:
            pattern: /
            stateless: true
            wsse:   true
        default:
            anonymous: ~
