security:
    providers:
        api_key_user_provider:
            id: api_key_user_provider
#        in_memory:
#            memory: ~      
#                users:
#                    ryan:
#                        password: ryanpass
#                        roles: 'ROLE_ADMIN'
#                    admin:
#                        password: password
#                        roles: 'ROLE_ADMIN'
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        blabla:
            pattern: /dash
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator
        default:
            anonymous: ~
#            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /dash
            logout:
                path:   /logout
                target: /
            
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        
    