security:
    providers:
        api_key_user_provider:
            id: api_key_user_provider
        in_memory:
            memory: ~
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        blabla:
            pattern: /
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator
        default:
            anonymous: ~
        