security:
    access_denied_url: /login
    providers:
        api_key_user_provider:
            id: api_key_user_provider
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        blabla:
            pattern: /dash
            stateless: true
            simple_preauth:
                authenticator: apikey_authenticator
        default:
            anonymous: ~
            form_login:
                login_path: /login
                default_target_path: /dash       
    access_control:
        - { path: ^/admin, roles: ROLE_ADMINISTRATOR }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        
    role_hierarchy:
        ROLE_VIEWER:    ROLE_USER
        ROLE_CONTRIBUTOR: [ROLE_VIEWER, ROLE_USER]
        ROLE_ADMINISTRATOR: [ROLE_CONTRIBUTOR, ROLE,VIEWER, ROLE_USER, ROLE_ALLOWED_TO_SWITCH]